title: mygqdblt's blog
baseurl: ""
url: "https://mygqdblt.github.io"
github_username:  mygqdblt

theme: minima
plugins:
  - jekyll-feed

disqus:
  shortname: gcnyin

minima:
  date_format: "%Y-%m-%d"
