baseURL: 'https://blog.boluotou.tech/'
languageCode: 'en-us'
title: '菠萝头'
subtitle: '一个充满好奇心的程序员'
theme: 'stack'
disqusShortname: gcnyin

hasCJKLanguage: true

params:
    sidebar:
        subtitle: 一个充满好奇心的程序员
        avatar:
            src: img/cat2.jpeg
    comments:
        enabled: true
        provider: utterances
        utterances:
            repo: gcnyin/gcnyin.github.io
            issueTerm: title
            label: comments
    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License
    widgets:
        homepage:
            - type: archives
              params:
                  path: /archives
                  limit: 30
            - type: tag-cloud
              params:
                  limit: 30
        page:
            - type: toc

menu:
    main: []
    social:
        - identifier: github
          name: GitHub
          url: https://github.com/gcnyin
          params:
              icon: brand-github

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
